[package]
name = "ceresdb-client-py"
version = "0.1.2"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module", "abi3-py37"] }
pyo3-asyncio = { version = "0.16", features = ["attributes", "tokio-runtime"] }
tokio = { version = "1", features = ["sync"] }

[dependencies.ceresdb-client-rs]
git = "https://github.com/CeresDB/ceresdb-client-rs.git"
rev = "dc3f84a19a941059ab9022b4f8376121551114dc"

[lib]
crate-type = ["cdylib"]
name = "ceresdb_client"

[patch.crates-io]
cmake = { git = "https://github.com/messense/cmake-rs.git", branch = "cross-compile" }

[build-dependencies]
cc = "1.0.73"
